### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by kyack** [jsebold666/RazorEnhanced#62]
In OSI, dress agent 'remove conflict' option does work weird with reward 'lantern of protection'  from hythloth event and spellbook. When I want to dress other spell book, the agent tries to remove lantern (even on left hand) and dress spell book (on right hand). In reverse case, same. If agent try to dress lantern, it remove spellbook (on right hand) and dress lantern (on left hand). It worked well with any other shields. Please check this issue. TY.

**Comment by vehumet** [comment]
I'm experiencing same issue.

I've inspected some lanterns in game, and showed they are lefthand layer and have two-hand flag.

This is same as two-handed weapons, so razor recognizes lantern as two-handed weapon, while it can be equipped with firstvalid equipment.

https://github.com/RazorEnhanced/RazorEnhanced/blob/3b26a0d12774877acb00efd66f9de352faafc633/Razor/RazorEnhanced/Dress.cs#L444

I'm not sure whether that is bug of assistant or uo client itself. I think it can be fixed by checking string "Two-handed Weapon" in item property near the above line.

**Comment by cesare-montresor** [comment]
We changed it to work with an external conig file, so it can be customized as needed, the (un)equip is governed by weapons.json:
https://github.com/RazorEnhanced/RazorEnhanced/blob/release/0.8/BuildSupplementalFiles/Config/weapons.json

In order to customize it:
1- Starting from the RazorEnhanced.exe main folder, you should find a weapons.json in the ./Config/ directory.
    Make a copy and move the copy to the ./Data/ folder, 
2- The new weapons.json can now be customized and overrides the main one.
3- Try to look for the ItemID of the wanted object of the item in the list, If you don't find it, add a fresh entry for the new item. 
4- You can then change the two-handed flag and the other properties to reflect the item.

Let us know if it works, so we can merge it back in the main file, in future releases.

**Comment by vehumet** [comment]
`
  {
    "name": "Lantern_on",
    "graphic": 0xA769,
    "primary": "1",
    "secondary": "1",
	"twohanded": false
  },  
  {
    "name": "Lantern_off",
    "graphic": 0xA76A,
    "primary": "1",
    "secondary": "1",
	"twohanded": false
  },  
  {
    "name": "lantern",
    "graphic": 0x0A22,
    "primary": "1",
    "secondary": "1",
	"twohanded": false
  },  
  {
    "name": "lantern",
    "graphic": 0x0A25,
    "primary": "1",
    "secondary": "1",
	"twohanded": false
  }`

I added these four elements and it works like a charm!
Lantern_on/Lantern_off are for _Lantern of Protection_ or _Wildfire Lantern_, and other two lanterns are just legacy lantern.
Thanks for your instruction.
